### ISSUE TITLE
write function "rename_s3_object()" for lambda

### ISSUE THREAD

**Issue by Chufle** [Chufle/kutter#58]

**Comment by Chufle** [comment]
rename not working. I made tests with rename or directly delete, both don't work. error message:
```
2022-11-30T18:04:47.515+01:00
[ERROR] ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied
Traceback (most recent call last):
  File "/var/task/photo_checkin.py", line 38, in handler
    rename_s3_object(bucket, object_id, file_name)
  File "/var/task/photo_checkin.py", line 20, in rename_s3_object
    s3.Object(bucket,old_file_name).delete()
  File "/var/runtime/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/var/runtime/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

I also get the error when I change policy document to allow all like this:
```
actions = [
        "s3:*",
        "s3-object-lambda:*"
    ]
    resources = [
        "arn:aws:s3:::${local.bucketname-photos}"
```

**Comment by Chufle** [comment]
done, now with two buckets upload and store

**Comment by Chufle** [comment]
changed to move_s3_object() function
